spring.application.name=address-api

springdoc.swagger-ui.path=/docs

# Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/address_db
spring.datasource.username=admin
spring.datasource.password=admin
api.url=http://localhost:3000

# Driver e Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect