spring.application.name=address-api

springdoc.swagger-ui.path=/docs

# Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/address_db
spring.datasource.username=admin
spring.datasource.password=admin
api.url=http://localhost:3000

# Driver e Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Resilience4j Circuit Breaker Config
resilience4j.circuitbreaker.instances.addressApi.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.addressApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.addressApi.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.addressApi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.addressApi.waitDurationInOpenState=15s
resilience4j.circuitbreaker.instances.addressApi.failureRateThreshold=50

# Monitoramento
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
